--- #YAML:1.0
name:                CPAN-PackageDetails
version:             0.11_01
abstract:            Create or read 02.packages.details.txt.gz
license:             perl
author:              
    - brian d foy <bdfoy@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    PerlIO::gzip:                  0
    Test::More:                    0
    Test::Output:                  0.10
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
