--- #YAML:1.0
name:               CPAN-PackageDetails
version:            0.17_03
abstract:           Create or read 02packages.details.txt.gz
author:
    - brian d foy <bdfoy@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    IO::Compress::Gzip:   0
    IO::Uncompress::Gunzip:  0
    Test::More:           0
    Test::Output:         0.10
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
