--- #YAML:1.0
name:                CPAN-PackageDetails
version:             0.20_01
abstract:            Create or read 02packages.details.txt.gz
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36_01
distribution_type:   module
requires:     
    IO::Compress::Gzip:            0
    IO::Uncompress::Gunzip:        0
    Test::More:                    0
    Test::Output:                  0.10
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - brian d foy <bdfoy@cpan.org>
